# Generated by Django 5.0 on 2023-12-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='mod_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
